[workspace.package]
version = "1.0.0"
edition = "2024"

[workspace]
resolver = "3"
members = [
    "crates/lambda-bytecode",
    "crates/lambda-core",
    "crates/lambda-parser"
, "crates/lambda-repl"]
