[package]
name = "lambda-bytecode"
version.workspace = true
edition.workspace = true

[dependencies]
lambda-parser = { path = "../lambda-parser" }
lambda-core = { path = "../lambda-core" }
bigdecimal.workspace = true
